apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homecraft-frontend
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ./front/chart
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  targetNamespace: default
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/naomauss/homecraft-frontend
      tag: "main-c6e42c9"
      pullPolicy: Always
    
    imagePullSecrets:
      - name: ghcr-secret
    
    replicaCount: 2
    
    service:
      type: ClusterIP
      port: 80
    
    ingress:
      enabled: true
      className: "traefik"
      annotations:
        # Allow access via IP address without hostname matching
        traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
      hosts:
        - host: homecraft.local
          paths:
            - path: /
              pathType: Prefix
        # Allow access via IP address (192.168.1.111)
        - host: "192.168.1.111"
          paths:
            - path: /
              pathType: Prefix
      tls: []
    
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
