apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homecraft-backend
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ./backend/chart
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  targetNamespace: default
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/naomauss/homecraft-backend
      tag: "main-c1358f2"
      pullPolicy: Always
    
    imagePullSecrets:
      - name: ghcr-secret
    
    replicaCount: 1
    
    service:
      type: ClusterIP
      port: 80
    
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi
    
    env:
      GIN_MODE: "release"
      PORT: "8080"
