apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-token
  namespace: default
type: Opaque
stringData:
  token: eyJhIjoiOTUzNTlhZTQ5MjEwOWI0NDgxOGFiZmRmZDk5M2YxMDUiLCJ0IjoiNDk4ZWViODAtZmI0OC00ZjU1LThkZDgtMjZlYTRmMDE5NTY0IiwicyI6Ill6azNaR1F6WVRBdE9HUTNZUzAwWWpZMkxXRTJZVEF0WVdFeFpqQmtNV0k1T0RSaiJ9
